export BACKGROUND_COLOR_DEFAULT=''

export BACKGROUND_COLOR_BLACK='\e[40m'
export BACKGROUND_COLOR_RED='\e[41m'
export BACKGROUND_COLOR_BLUE='\e[42m'
export BACKGROUND_COLOR_YELLOW='\e[43m'
export BACKGROUND_COLOR_GREEN='\e[44m'
export BACKGROUND_COLOR_MAJENTA='\e[45m'
export BACKGROUND_COLOR_CYAN='\e[46m'
export BACKGROUND_COLOR_WHITE='\e[47m'

export BACHGROUND_COLOR_STOP='\e[m'